### ISSUE TITLE
Non-integer intervals are always regarded as non-uniform

### ISSUE THREAD

**Issue by jonasoh** [aravind-j/germinationmetrics#3]
The check `if (length(unique(diff(intervals))) != 1)` (line 113, t50.R) does not correctly handle non-integer intervals. This is, I believe, due to how R stores floats. 

To reproduce:
```
intervals <- seq(1,10) * 0.48
counts <- as.integer(rnorm(10, 2))
t50(intervals = intervals, germ.counts = counts, method="coolbear")
```

Output (using latest development version):
```
> t50(intervals = intervals, germ.counts = counts, method="coolbear")
[1] 3.44
Warning message:
In t50(intervals = intervals, germ.counts = counts, method = "coolbear") :
  'intervals' are not uniform.
```

This is especially problematic when using the release version of the package, which will regard this as an error.

**Comment by aravind-j** [comment]
Good catch @jonasoh.

Fixed the check as follows

```
idiff <- diff(intervals)
if (!all(abs(idiff - idiff[[1]]) < .Machine$double.eps ^ 0.5)) {
  warning("'intervals' are not uniform.")
}
````

**Comment by jonasoh** [comment]
I notice that the fix for this bug has not been incorporated into the CRAN releases of germinationmetrics. Is there a reason for this? Will the bugfix make it into CRAN at some point?
