### ISSUE TITLE
Issue with t50 computation

### ISSUE THREAD

**Issue by amaugarn** [aravind-j/germinationmetrics#7]
Dear authors,
I have recently used your package to compute t50 on cumulative germination counts. Unfortunately the results I get do not match what I should get. I copy paste some exemples bellow.
Could you please have a look at this strage behavior.
Thank you very much,
Aude Maugarny

> y <- c(0 , 0 , 0 ,39 ,41, 41)
> int <- c(0, 1, 2, 3, 4, 7)
> t50(germ.counts = y, intervals = int, partial = FALSE, method = "farooq")
[1] 1.576923
Warning message:
In t50(germ.counts = y, intervals = int, partial = FALSE, method = "farooq") :
  'intervals' are not uniform.
> y <- c( 0 , 0 ,39 ,41, 41)
> int <- c( 1, 2, 3, 4, 7)
> t50(germ.counts = y, intervals = int, partial = FALSE, method = "farooq")
[1] 2.051282
Warning message:
In t50(germ.counts = y, intervals = int, partial = FALSE, method = "farooq") :
  'intervals' are not uniform.
> y <- c( 0 ,39 ,41, 41)
> int <- c(2, 3, 4, 7)
> t50(germ.counts = y, intervals = int, partial = FALSE, method = "farooq")
[1] 2.525641
Warning message:
In t50(germ.counts = y, intervals = int, partial = FALSE, method = "farooq") :
  'intervals' are not uniform.
> y <- c(0 , 0 , 0 ,39 ,41)
> int <- c(0, 1, 2, 3, 4)
> t50(germ.counts = y, intervals = int, partial = FALSE, method = "farooq")
[1] 1.576923

**Comment by aravind-j** [comment]
Good catch. Yes it is a bug. Will be fixed in the next release.
